version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rsdmp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rsdmp
    ports:
      - "5432:5432"
    volumes:
      - rsdmp_pgdata:/var/lib/postgresql/data

volumes:
  rsdmp_pgdata: